use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::io::{self, Write};

/// Project-level configuration stored in `codexa.toml`
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Config {
    pub project: ProjectConfig,
    pub scan: ScanConfig,
    pub output: OutputConfig,
    /// Optional vector database — disabled by default
    #[serde(default)]
    pub vector: Option<VectorConfig>,
}

// ── Vector DB config ──────────────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct VectorConfig {
    /// Which backend to use
    #[serde(default)]
    pub backend: VectorBackend,
    /// Embedding provider
    #[serde(default)]
    pub embedding: EmbeddingProvider,
    /// Chunk size in lines
    #[serde(default = "default_chunk_size")]
    pub chunk_size: usize,
    /// Overlap between chunks in lines
    #[serde(default = "default_overlap")]
    pub overlap: usize,
    /// Embedding batch size (how many chunks sent per API call)
    #[serde(default = "default_batch_size")]
    pub batch_size: usize,
}

fn default_chunk_size() -> usize { 60 }
fn default_overlap() -> usize { 10 }
fn default_batch_size() -> usize { 32 }

impl Default for VectorConfig {
    fn default() -> Self {
        VectorConfig {
            backend: VectorBackend::Sqlite {
                path: ".codexa/index.db".into(),
            },
            embedding: EmbeddingProvider::Ollama {
                base_url: "http://localhost:11434".into(),
                model: "nomic-embed-text".into(),
                dimensions: 768,
            },
            chunk_size: default_chunk_size(),
            overlap: default_overlap(),
            batch_size: default_batch_size(),
        }
    }
}

/// Which vector store backend to use.
#[derive(Debug, Serialize, Deserialize, Clone, Default)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum VectorBackend {
    /// No vector DB — context generated by re-scanning every time
    #[default]
    None,
    /// SQLite with sqlite-vec extension (zero setup, single file)
    Sqlite {
        /// Path to the .db file (relative to project root)
        path: String,
    },
    /// PostgreSQL with pgvector extension
    Postgres {
        /// Full libpq connection string, e.g. "host=localhost dbname=codexa user=dev"
        connection_string: String,
    },
}

/// Where to fetch embeddings from.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(tag = "provider", rename_all = "lowercase")]
pub enum EmbeddingProvider {
    /// OpenAI embeddings API
    OpenAI {
        api_key: String,
        #[serde(default = "default_openai_model")]
        model: String,
    },
    /// Any OpenAI-compatible API (Together, Mistral, local LM Studio, etc.)
    #[serde(rename = "openai_compatible")]
    OpenAICompatible {
        api_base: String,
        #[serde(default)]
        api_key: Option<String>,
        model: String,
        #[serde(default = "default_dimensions")]
        dimensions: usize,
    },
    /// Ollama — runs locally, no API key needed
    Ollama {
        #[serde(default = "default_ollama_url")]
        base_url: String,
        #[serde(default = "default_ollama_model")]
        model: String,
        #[serde(default = "default_dimensions")]
        dimensions: usize,
    },
    /// Local ONNX — runs locally using ort + tokenizers
    #[serde(rename = "local_onnx")]
    LocalOnnx {
        model_path: String,
        tokenizer_path: String,
        #[serde(default = "default_dimensions")]
        dimensions: usize,
    },
}

fn default_openai_model() -> String { "text-embedding-3-small".into() }
fn default_ollama_url() -> String { "http://localhost:11434".into() }
fn default_ollama_model() -> String { "nomic-embed-text".into() }
fn default_dimensions() -> usize { 768 }

impl Default for EmbeddingProvider {
    fn default() -> Self {
        EmbeddingProvider::Ollama {
            base_url: default_ollama_url(),
            model: default_ollama_model(),
            dimensions: default_dimensions(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ProjectConfig {
    pub name: String,
    pub description: String,
    pub main_language: String,
    pub team_size: Option<u32>,
    pub custom_notes: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ScanConfig {
    /// Extra dirs to exclude beyond .gitignore
    pub exclude_dirs: Vec<String>,
    /// File extensions to include (empty = all)
    pub include_extensions: Vec<String>,
    /// Max file size in KB to index content (not just path)
    pub max_file_size_kb: u64,
    /// Max depth to traverse
    pub max_depth: usize,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct OutputConfig {
    pub output_file: String,
    /// Include file tree in output
    pub include_tree: bool,
    /// Include key file snippets
    pub include_snippets: bool,
    /// Max lines per snippet
    pub snippet_lines: usize,
    /// Extra free-form instructions for AI agents
    pub agent_instructions: Option<String>,
}

impl Default for Config {
    fn default() -> Self {
        Config {
            project: ProjectConfig {
                name: "my-project".into(),
                description: "A software project".into(),
                main_language: "unknown".into(),
                team_size: None,
                custom_notes: None,
            },
            vector: None,
            scan: ScanConfig {
                exclude_dirs: vec![
                    "node_modules".into(),
                    "target".into(),
                    ".git".into(),
                    "dist".into(),
                    "build".into(),
                    ".next".into(),
                    "__pycache__".into(),
                    "vendor".into(),
                ],
                include_extensions: vec![],
                max_file_size_kb: 512,
                max_depth: 10,
            },
            output: OutputConfig {
                output_file: "AGENTS.md".into(),
                include_tree: true,
                include_snippets: true,
                snippet_lines: 30,
                agent_instructions: Some(
                    "Follow existing code style. Ask before making large refactors.".into(),
                ),
            },
        }
    }
}

impl Config {
    pub fn load_or_default(path: &str) -> Self {
        let config_path = format!("{}/codexa.toml", path);
        if let Ok(content) = std::fs::read_to_string(&config_path) {
            toml::from_str(&content).unwrap_or_default()
        } else {
            Config::default()
        }
    }

    pub fn save(&self, path: &str) -> Result<()> {
        let config_path = format!("{}/codexa.toml", path);
        let content = toml::to_string_pretty(self)?;
        std::fs::write(config_path, content)?;
        Ok(())
    }

    /// Simple interactive wizard (no external TUI deps — keeps MVP lean)
    pub fn interactive_create(path: &str) -> Result<Self> {
        let mut cfg = Config::load_or_default(path);

        cfg.project.name = prompt("Project name", &cfg.project.name)?;
        cfg.project.description = prompt("Short description", &cfg.project.description)?;
        cfg.project.main_language = prompt("Main language (rust/typescript/python/...)", &cfg.project.main_language)?;

        let instructions_default = cfg
            .output
            .agent_instructions
            .clone()
            .unwrap_or_default();
        let instructions = prompt("Agent instructions (rules for the AI)", &instructions_default)?;
        cfg.output.agent_instructions = if instructions.is_empty() {
            None
        } else {
            Some(instructions)
        };

        let notes = prompt("Extra notes for AI (optional)", "")?;
        cfg.project.custom_notes = if notes.is_empty() { None } else { Some(notes) };

        let include_snippets = prompt("Include key file snippets? (y/n)", "y")?;
        cfg.output.include_snippets = include_snippets.trim().to_lowercase() != "n";

        Ok(cfg)
    }
}

fn prompt(label: &str, default: &str) -> Result<String> {
    if default.is_empty() {
        print!("  {} : ", label);
    } else {
        print!("  {} [{}] : ", label, default);
    }
    io::stdout().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let trimmed = input.trim().to_string();

    Ok(if trimmed.is_empty() {
        default.to_string()
    } else {
        trimmed
    })
}

impl Config {
    /// Append vector wizard logic — called by interactive_create after base config.
    pub fn configure_vector_wizard(&mut self) -> Result<()> {
        use colored::Colorize;

        println!();
        println!("  {} Vector database speeds up search on large projects.", "→".cyan());
        println!("    Backends: {} (zero setup) | {} (needs pgvector)", "sqlite".bold(), "postgres".bold());

        let use_vector = prompt("Enable vector database? (y/n)", "n")?;
        if use_vector.trim().to_lowercase() != "y" {
            self.vector = None;
            return Ok(());
        }

        let backend_choice = prompt("Backend: sqlite or postgres", "sqlite")?;
        let backend = if backend_choice.trim() == "postgres" {
            let conn = prompt(
                "PostgreSQL connection string",
                "host=localhost dbname=codexa user=dev password=dev",
            )?;
            VectorBackend::Postgres { connection_string: conn }
        } else {
            let db_path = prompt("SQLite DB path", ".codexa/index.db")?;
            VectorBackend::Sqlite { path: db_path }
        };

        println!();
        println!("  Embedding provider:");
        println!("    2) openai  — cloud, accurate");
        println!("    3) openai_compatible — any compatible API");
        println!("    4) local_onnx — local, private, no external deps (advanced)");
        let emb_choice = prompt("Provider (1-4)", "1")?;

        let embedding = match emb_choice.trim() {
            "2" => {
                let key = prompt("OpenAI API key", "")?;
                EmbeddingProvider::OpenAI {
                    api_key: key,
                    model: "text-embedding-3-small".into(),
                }
            }
            "3" => {
                let base = prompt("API base URL", "http://localhost:8080/v1")?;
                let model = prompt("Model name", "nomic-embed-text")?;
                let dims: usize = prompt("Embedding dimensions", "768")?.parse().unwrap_or(768);
                EmbeddingProvider::OpenAICompatible {
                    api_base: base,
                    api_key: None,
                    model,
                    dimensions: dims,
                }
            }
            "4" => {
                let m_path = prompt("Path to model (.onnx)", ".codexa/models/model.onnx")?;
                let t_path = prompt("Path to tokenizer.json", ".codexa/models/tokenizer.json")?;
                let dims: usize = prompt("Embedding dimensions", "384")?.parse().unwrap_or(384);
                EmbeddingProvider::LocalOnnx {
                    model_path: m_path,
                    tokenizer_path: t_path,
                    dimensions: dims,
                }
            }
            _ => EmbeddingProvider::Ollama {
                base_url: "http://localhost:11434".into(),
                model: "nomic-embed-text".into(),
                dimensions: 768,
            },
        };

        self.vector = Some(VectorConfig { backend, embedding, ..VectorConfig::default() });
        Ok(())
    }
}
