use crate::config::Config;
use crate::indexer::ProjectIndex;
use anyhow::Result;

/// Write a compact Markdown context file optimised for AI agents.
/// Every section is clearly labeled so agents can parse it.
pub fn write_markdown(index: &ProjectIndex, output_path: &str, cfg: &Config) -> Result<()> {
    let mut out = String::new();

    // ── Header ──────────────────────────────────────────────────────────────
    out.push_str(&format!(
        "# {} — AI Context\n\n",
        cfg.project.name
    ));
    out.push_str(&format!(
        "> Generated by [codexa](https://github.com/yourname/codexa) on {}\n\n",
        index.scanned_at
    ));

    // ── Project Overview ─────────────────────────────────────────────────────
    out.push_str("## Project Overview\n\n");
    out.push_str(&format!("**Description:** {}\n\n", cfg.project.description));
    out.push_str(&format!("**Primary Language:** {}\n\n", cfg.project.main_language));
    out.push_str(&format!(
        "**Size:** {} files · {} lines of code\n\n",
        index.total_files, index.total_lines
    ));

    if let Some(ref notes) = cfg.project.custom_notes {
        out.push_str(&format!("**Notes:** {}\n\n", notes));
    }

    // ── Agent Instructions ────────────────────────────────────────────────────
    if let Some(ref instructions) = cfg.output.agent_instructions {
        out.push_str("## Instructions for AI Agent\n\n");
        out.push_str(instructions);
        out.push_str("\n\n");
    }

    // ── Languages ─────────────────────────────────────────────────────────────
    out.push_str("## Languages Detected\n\n");
    let mut langs: Vec<_> = index.languages.iter().collect();
    langs.sort_by(|a, b| b.1.cmp(a.1));
    for (lang, count) in &langs {
        out.push_str(&format!("- **{}**: {} files\n", lang, count));
    }
    out.push('\n');

    // ── Entry Points ──────────────────────────────────────────────────────────
    if !index.entry_points.is_empty() {
        out.push_str("## Entry Points\n\n");
        for ep in &index.entry_points {
            out.push_str(&format!("- `{}`\n", ep));
        }
        out.push('\n');
    }

    // ── Key Files ─────────────────────────────────────────────────────────────
    if !index.key_files.is_empty() {
        out.push_str("## Key Files\n\n");
        out.push_str("| File | Purpose |\n");
        out.push_str("|------|---------|\n");
        for kf in &index.key_files {
            out.push_str(&format!("| `{}` | {} |\n", kf.path, kf.reason));
        }
        out.push('\n');

        // Snippets
        if cfg.output.include_snippets {
            for kf in index.key_files.iter().filter(|f| f.snippet.is_some()) {
                if let Some(ref snippet) = kf.snippet {
                    out.push_str(&format!("### `{}`\n\n", kf.path));
                    out.push_str("```\n");
                    out.push_str(snippet);
                    out.push_str("\n```\n\n");
                }
            }
        }
    }

    // ── Dependencies ──────────────────────────────────────────────────────────
    if !index.dependencies.is_empty() {
        out.push_str("## Dependencies (top)\n\n");
        for dep in index.dependencies.iter().take(30) {
            out.push_str(&format!("- `{}`\n", dep));
        }
        out.push('\n');
    }

    // ── File Tree ─────────────────────────────────────────────────────────────
    if cfg.output.include_tree {
        out.push_str("## File Tree\n\n");
        out.push_str("```\n");
        let tree = render_tree(&index.file_tree, 60);
        out.push_str(&tree);
        out.push_str("```\n\n");
    }

    // ── Footer ────────────────────────────────────────────────────────────────
    out.push_str("---\n");
    out.push_str("*This file was auto-generated by codexa. Re-run `codexa update` after major changes.*\n");

    std::fs::write(output_path, out)?;
    Ok(())
}

/// Write machine-readable JSON for programmatic use (MCP, custom agents, etc.)
pub fn write_json(index: &ProjectIndex, output_path: &str) -> Result<()> {
    let json = serde_json::to_string_pretty(index)?;
    std::fs::write(output_path, json)?;
    Ok(())
}

/// Render a compact file tree (max `limit` entries)
fn render_tree(files: &[crate::indexer::FileNode], limit: usize) -> String {
    let mut lines: Vec<String> = files
        .iter()
        .take(limit)
        .map(|f| format!("  {}", f.path))
        .collect();

    if files.len() > limit {
        lines.push(format!("  ... and {} more files", files.len() - limit));
    }

    lines.join("\n")
}
